const express = require('express')
const route = express.Router()
const { Auth, isUser, isRecruiter, isApprovedRecruiter } = require('../Middlewares/Auth')
const c = require('../controllers/Career')
route.get('/career/overview', Auth, isUser, c.getOverview)
route.post('/career/match', Auth, isUser, c.smartMatch)
route.post('/career/roadmap', Auth, isUser, c.createRoadmap)
route.get('/career/follow-ups', Auth, isUser, c.listFollowUps)
route.post('/career/follow-ups', Auth, isUser, c.createFollowUp)
route.patch('/career/follow-ups/:followUpId', Auth, isUser, c.toggleFollowUp)
route.get('/career/profile', Auth, isUser, c.getProfile)
route.post('/career/profile/share', Auth, isUser, c.shareProfile)
route.get('/public/career/:shareId', c.getSharedProfile)
route.get('/public/jobs/:jobId/trust', c.jobTrust)
route.post('/career/interview-feedback', Auth, isUser, c.interviewFeedback)
route.get('/jobs/:jobId/candidate-matches', Auth, isRecruiter, isApprovedRecruiter, c.recruiterMatches)
module.exports = route
