import { useEffect, useState } from 'react'
import { useSelector } from 'react-redux'
import { Link } from 'react-router'
import { Helmet } from 'react-helmet-async'
import DashboardLayout from './DashboardLayout'
import Loading from '../extra/Loading'
import { apiConnector } from '../../Services/apiConnector'
import { CareerApi } from '../../Services/Apis/CareerApi'

const Card = ({ title, children }) => <section className="rounded-2xl bg-richblack-800 p-5 shadow-md"><h2 className="text-sm font-semibold text-richblack-5 mb-3">{title}</h2>{children}</section>

export default function CareerCopilot() {
  const { token } = useSelector(s => s.auth); const [data, setData] = useState(null); const [jobText, setJobText] = useState(''); const [role, setRole] = useState(''); const [roadmap, setRoadmap] = useState(null); const [copilot, setCopilot] = useState(null); const [feedback, setFeedback] = useState(null); const [question, setQuestion] = useState('Tell me about a project you are proud of.'); const [answer, setAnswer] = useState(''); const [followUp, setFollowUp] = useState({ title: '', dueAt: '' }); const [busy, setBusy] = useState(false); const [analyzing, setAnalyzing] = useState(false)
  const load = async () => { const r = await apiConnector('GET', CareerApi.overview, null, { Authorization: `Bearer ${token}` }); setData(r.data) }
  useEffect(() => { let alive = true; apiConnector('GET', CareerApi.overview, null, { Authorization: `Bearer ${token}` }).then(r => { if (alive) setData(r.data) }).catch(() => {}); return () => { alive = false } }, [token])
  if (!data) return <DashboardLayout title="Career Copilot"><Loading text="Loading Career Copilot..." /></DashboardLayout>
  const analyzeApplication = async () => {
    if (!jobText.trim()) return
    setAnalyzing(true)
    try {
      const r = await apiConnector('POST', CareerApi.applicationCopilot, { jobText }, { Authorization: `Bearer ${token}` })
      setCopilot(r.data)
    } finally {
      setAnalyzing(false)
    }
  }
  const makeRoadmap = async e => { e.preventDefault(); setBusy(true); try { const r = await apiConnector('POST', CareerApi.roadmap, { targetRole: role, jobText }, { Authorization: `Bearer ${token}` }); setRoadmap(r.data) } finally { setBusy(false) } }
  const reviewAnswer = async e => { e.preventDefault(); const r = await apiConnector('POST', CareerApi.interviewFeedback, { question, answer }, { Authorization: `Bearer ${token}` }); setFeedback(r.data.feedback) }
  const addFollowUp = async e => { e.preventDefault(); await apiConnector('POST', CareerApi.followUps, followUp, { Authorization: `Bearer ${token}` }); setFollowUp({ title: '', dueAt: '' }); load() }
  const toggleFollowUp = async item => { await apiConnector('PATCH', `${CareerApi.followUps}/${item._id}`, { completed: !item.completed }, { Authorization: `Bearer ${token}` }); load() }
  const shareProfile = async () => { const r = await apiConnector('POST', CareerApi.profileShare, null, { Authorization: `Bearer ${token}` }); if (r.data.shareId) navigator.clipboard?.writeText(`${window.location.origin}/Career/${r.data.shareId}`) }
  return <DashboardLayout title="Career Copilot"><Helmet><title>Career Copilot | Resumify</title></Helmet><p className="text-sm text-richblack-400 px-4 lg:px-6 pt-4">Turn every job opportunity into a clear next step.</p><div className="max-w-5xl mx-auto space-y-6 px-4 lg:px-6 py-4">
    <Card title="Application Copilot"><p className="text-xs text-richblack-400 mb-3">Paste a job description and get a practical application plan using {data.resume ? (data.resume.label || 'your saved resume') : 'your saved resume'}.</p><textarea value={jobText} onChange={e => setJobText(e.target.value)} placeholder="Paste the job description here..." className="w-full min-h-28 rounded-lg bg-richblack-900 border border-richblack-700 p-3 text-sm text-richblack-5" /><div className="flex flex-wrap gap-2 mt-3"><button type="button" disabled={analyzing || !jobText.trim()} onClick={analyzeApplication} className="rounded-lg bg-yellow-50 px-4 py-2 text-sm font-semibold text-richblack-900">{analyzing ? 'Analyzing...' : 'Analyze application'}</button><button type="button" disabled={busy || !jobText.trim()} onClick={makeRoadmap} className="rounded-lg border border-richblack-600 px-4 py-2 text-sm text-richblack-200">{busy ? 'Building...' : 'Build skill roadmap'}</button></div>{copilot && <div className="mt-5 space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs text-richblack-400">Resume fit</p><p className="font-display text-4xl text-yellow-50">{copilot.fit.score}%</p><p className="text-sm text-richblack-200">{copilot.fit.tier}</p></div>{copilot.recommendedResume && <div className="text-right"><p className="text-xs text-richblack-400">Recommended built resume</p><p className="text-sm font-semibold text-richblack-5">{copilot.recommendedResume.title} · {copilot.recommendedResume.score}%</p></div>}</div><div><p className="text-xs text-richblack-400 mb-2">Missing or weak keywords</p>{copilot.fit.missing.length ? copilot.fit.missing.slice(0, 10).map(s => <span key={s} className="inline-block mr-2 mb-2 rounded-full bg-pink-900/30 px-2 py-1 text-xs text-pink-100">{s}</span>) : <p className="text-sm text-caribgreen-100">Your resume covers the main terms in this job.</p>}</div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2">{copilot.checklist.map(item => <Link key={item.key} to={item.action} className={`rounded-lg border p-3 text-xs ${item.complete ? 'border-caribgreen-700/60 bg-caribgreen-900/15 text-caribgreen-100' : 'border-richblack-700 bg-richblack-900/50 text-richblack-200 hover:border-yellow-50/50'}`}><span className="block font-semibold">{item.complete ? '✓ ' : '→ '}{item.label}</span>{!item.complete && <span className="text-richblack-400">Open next</span>}</Link>)}</div>{copilot.nextSteps.length > 0 && <div className="rounded-lg bg-richblack-900/60 p-3"><p className="text-xs font-semibold text-richblack-300 mb-1">Before you apply</p>{copilot.nextSteps.map(step => <p key={step} className="text-xs text-richblack-400">• {step}</p>)}</div>}</div>}</Card>
    <Card title="Skill roadmap workspace"><form onSubmit={makeRoadmap} className="flex gap-2 mt-3"><input value={role} onChange={e => setRole(e.target.value)} placeholder="Target role (optional)" className="flex-1 rounded-lg bg-richblack-900 border border-richblack-700 px-3 py-2 text-sm text-richblack-5" /><button disabled={busy || !jobText.trim()} className="rounded-lg bg-caribgreen-700 px-4 py-2 text-sm font-semibold text-white">{busy ? 'Building...' : 'Build roadmap'}</button></form>{roadmap && <div className="mt-4 grid md:grid-cols-2 gap-3"><div><p className="text-xs text-richblack-400">Current match</p><p className="font-display text-3xl text-yellow-50">{roadmap.match.score}%</p><p className="text-sm text-richblack-200">{roadmap.match.tier}</p></div><div><p className="text-xs text-richblack-400 mb-2">Priority skill gaps</p>{roadmap.plan.skills.slice(0, 6).map(s => <span key={s.name} className="inline-block mr-2 mb-2 rounded-full bg-pink-900/30 px-2 py-1 text-xs text-pink-100">{s.name}</span>)}</div></div>}</Card>
    <div className="grid lg:grid-cols-2 gap-6"><Card title="Application follow-ups"><form onSubmit={addFollowUp} className="space-y-2"><input required value={followUp.title} onChange={e => setFollowUp({ ...followUp, title: e.target.value })} placeholder="Follow up with Acme" className="w-full rounded-lg bg-richblack-900 border border-richblack-700 px-3 py-2 text-sm text-richblack-5" /><input required type="datetime-local" value={followUp.dueAt} onChange={e => setFollowUp({ ...followUp, dueAt: e.target.value })} className="w-full rounded-lg bg-richblack-900 border border-richblack-700 px-3 py-2 text-sm text-richblack-5" /><button className="rounded-lg bg-caribgreen-700 px-3 py-2 text-sm text-white">Add reminder</button></form><div className="mt-4 space-y-2">{data.followUps.map(f => <button type="button" onClick={() => toggleFollowUp(f)} key={f._id} className="w-full flex justify-between rounded-lg bg-richblack-900/70 p-3 text-sm text-left"><span className={f.completed ? 'line-through text-richblack-500' : 'text-richblack-200'}>{f.title}</span><span className="text-xs text-richblack-400">{new Date(f.dueAt).toLocaleDateString()}</span></button>)}</div></Card>
    <Card title="Interview feedback"><input value={question} onChange={e => setQuestion(e.target.value)} className="w-full mb-2 rounded-lg bg-richblack-900 border border-richblack-700 px-3 py-2 text-sm text-richblack-5" /><textarea value={answer} onChange={e => setAnswer(e.target.value)} placeholder="Write your answer..." className="w-full min-h-24 rounded-lg bg-richblack-900 border border-richblack-700 p-3 text-sm text-richblack-5" /><button onClick={reviewAnswer} className="mt-2 rounded-lg bg-yellow-50 px-3 py-2 text-sm font-semibold text-richblack-900">Review answer</button>{feedback && <div className="mt-4"><p className="font-display text-3xl text-yellow-50">{feedback.score}/100</p>{feedback.improvements.map(x => <p key={x} className="text-sm text-richblack-300 mt-2">{x}</p>)}</div>}</Card></div>
    <Card title="Your job matches"><button onClick={shareProfile} className="mb-3 rounded-lg border border-richblack-600 px-3 py-2 text-xs text-richblack-200">Share career profile</button>{data.matches.length ? data.matches.map(m => <div key={m.applicationId} className="flex justify-between border-b border-richblack-700 py-3"><div><p className="text-sm text-richblack-5">{m.job.title}</p><p className="text-xs text-richblack-400">{m.job.companyName}</p></div><span className="font-semibold text-yellow-50">{m.match.score}% match</span></div>) : <p className="text-sm text-richblack-400">Apply to jobs to see your matches here.</p>}</Card>
  </div></DashboardLayout>
}
