import { useEffect, useState } from 'react'
import { useSelector } from 'react-redux'
import { Helmet } from 'react-helmet-async'
import DashboardLayout from './DashboardLayout'
import Loading from '../extra/Loading'
import { apiConnector } from '../../Services/apiConnector'
import { CareerApi } from '../../Services/Apis/CareerApi'

const Card = ({ title, children }) => <section className="rounded-2xl bg-richblack-800 p-5 shadow-md"><h2 className="text-sm font-semibold text-richblack-5 mb-3">{title}</h2>{children}</section>

export default function CareerCopilot() {
  const { token } = useSelector(s => s.auth); const [data, setData] = useState(null); const [jobText, setJobText] = useState(''); const [role, setRole] = useState(''); const [roadmap, setRoadmap] = useState(null); const [feedback, setFeedback] = useState(null); const [question, setQuestion] = useState('Tell me about a project you are proud of.'); const [answer, setAnswer] = useState(''); const [followUp, setFollowUp] = useState({ title: '', dueAt: '' }); const [busy, setBusy] = useState(false)
  const load = async () => { const r = await apiConnector('GET', CareerApi.overview, null, { Authorization: `Bearer ${token}` }); setData(r.data) }
  useEffect(() => { let alive = true; apiConnector('GET', CareerApi.overview, null, { Authorization: `Bearer ${token}` }).then(r => { if (alive) setData(r.data) }).catch(() => {}); return () => { alive = false } }, [token])
  if (!data) return <DashboardLayout><Loading text="Loading Career Copilot..." /></DashboardLayout>
  const makeRoadmap = async e => { e.preventDefault(); setBusy(true); try { const r = await apiConnector('POST', CareerApi.roadmap, { targetRole: role, jobText }, { Authorization: `Bearer ${token}` }); setRoadmap(r.data) } finally { setBusy(false) } }
  const reviewAnswer = async e => { e.preventDefault(); const r = await apiConnector('POST', CareerApi.interviewFeedback, { question, answer }, { Authorization: `Bearer ${token}` }); setFeedback(r.data.feedback) }
  const addFollowUp = async e => { e.preventDefault(); await apiConnector('POST', CareerApi.followUps, followUp, { Authorization: `Bearer ${token}` }); setFollowUp({ title: '', dueAt: '' }); load() }
  const toggleFollowUp = async item => { await apiConnector('PATCH', `${CareerApi.followUps}/${item._id}`, { completed: !item.completed }, { Authorization: `Bearer ${token}` }); load() }
  const shareProfile = async () => { const r = await apiConnector('POST', CareerApi.profileShare, null, { Authorization: `Bearer ${token}` }); if (r.data.shareId) navigator.clipboard?.writeText(`${window.location.origin}/Career/${r.data.shareId}`) }
  return <DashboardLayout><Helmet><title>Career Copilot | Resumify</title></Helmet><div className="max-w-5xl space-y-6"><div><h1 className="font-display text-2xl text-richblack-5">Career Copilot</h1><p className="text-sm text-richblack-400 mt-1">Turn every job opportunity into a clear next step.</p></div>
    <Card title="Your job match workspace"><p className="text-xs text-richblack-400 mb-3">{data.resume ? `Using ${data.resume.label || 'your default resume'}` : 'Save a resume first to unlock matching.'}</p><textarea value={jobText} onChange={e => setJobText(e.target.value)} placeholder="Paste a job description to generate your skill gap and action plan..." className="w-full min-h-28 rounded-lg bg-richblack-900 border border-richblack-700 p-3 text-sm text-richblack-5" /><form onSubmit={makeRoadmap} className="flex gap-2 mt-3"><input value={role} onChange={e => setRole(e.target.value)} placeholder="Target role (optional)" className="flex-1 rounded-lg bg-richblack-900 border border-richblack-700 px-3 py-2 text-sm text-richblack-5" /><button disabled={busy} className="rounded-lg bg-yellow-50 px-4 py-2 text-sm font-semibold text-richblack-900">{busy ? 'Building...' : 'Build roadmap'}</button></form>{roadmap && <div className="mt-4 grid md:grid-cols-2 gap-3"><div><p className="text-xs text-richblack-400">Current match</p><p className="font-display text-3xl text-yellow-50">{roadmap.match.score}%</p><p className="text-sm text-richblack-200">{roadmap.match.tier}</p></div><div><p className="text-xs text-richblack-400 mb-2">Priority skill gaps</p>{roadmap.plan.skills.slice(0, 6).map(s => <span key={s.name} className="inline-block mr-2 mb-2 rounded-full bg-pink-900/30 px-2 py-1 text-xs text-pink-100">{s.name}</span>)}</div></div>}</Card>
    <div className="grid lg:grid-cols-2 gap-6"><Card title="Application follow-ups"><form onSubmit={addFollowUp} className="space-y-2"><input required value={followUp.title} onChange={e => setFollowUp({ ...followUp, title: e.target.value })} placeholder="Follow up with Acme" className="w-full rounded-lg bg-richblack-900 border border-richblack-700 px-3 py-2 text-sm text-richblack-5" /><input required type="datetime-local" value={followUp.dueAt} onChange={e => setFollowUp({ ...followUp, dueAt: e.target.value })} className="w-full rounded-lg bg-richblack-900 border border-richblack-700 px-3 py-2 text-sm text-richblack-5" /><button className="rounded-lg bg-caribgreen-700 px-3 py-2 text-sm text-white">Add reminder</button></form><div className="mt-4 space-y-2">{data.followUps.map(f => <button type="button" onClick={() => toggleFollowUp(f)} key={f._id} className="w-full flex justify-between rounded-lg bg-richblack-900/70 p-3 text-sm text-left"><span className={f.completed ? 'line-through text-richblack-500' : 'text-richblack-200'}>{f.title}</span><span className="text-xs text-richblack-400">{new Date(f.dueAt).toLocaleDateString()}</span></button>)}</div></Card>
    <Card title="Interview feedback"><input value={question} onChange={e => setQuestion(e.target.value)} className="w-full mb-2 rounded-lg bg-richblack-900 border border-richblack-700 px-3 py-2 text-sm text-richblack-5" /><textarea value={answer} onChange={e => setAnswer(e.target.value)} placeholder="Write your answer..." className="w-full min-h-24 rounded-lg bg-richblack-900 border border-richblack-700 p-3 text-sm text-richblack-5" /><button onClick={reviewAnswer} className="mt-2 rounded-lg bg-yellow-50 px-3 py-2 text-sm font-semibold text-richblack-900">Review answer</button>{feedback && <div className="mt-4"><p className="font-display text-3xl text-yellow-50">{feedback.score}/100</p>{feedback.improvements.map(x => <p key={x} className="text-sm text-richblack-300 mt-2">{x}</p>)}</div>}</Card></div>
    <Card title="Your job matches"><button onClick={shareProfile} className="mb-3 rounded-lg border border-richblack-600 px-3 py-2 text-xs text-richblack-200">Share career profile</button>{data.matches.length ? data.matches.map(m => <div key={m.applicationId} className="flex justify-between border-b border-richblack-700 py-3"><div><p className="text-sm text-richblack-5">{m.job.title}</p><p className="text-xs text-richblack-400">{m.job.companyName}</p></div><span className="font-semibold text-yellow-50">{m.match.score}% match</span></div>) : <p className="text-sm text-richblack-400">Apply to jobs to see your matches here.</p>}</Card>
  </div></DashboardLayout>
}
