import LegalPage from './LegalPage'

const TermsAndConditions = () => (
  <LegalPage title="Terms & Conditions" updatedAt="August 24, 2026">
    <section>
      <h2>1. Agreement to these terms</h2>
      <p>
        By creating an account or using Resumify, you agree to these Terms & Conditions. If you
        don't agree, please don't use the service.
      </p>
    </section>

    <section>
      <h2>2. Your account</h2>
      <ul>
        <li>You must provide accurate information when signing up and keep your login credentials confidential.</li>
        <li>You're responsible for all activity that happens under your account.</li>
        <li>You must be old enough to legally enter into an agreement in your jurisdiction to use Resumify.</li>
        <li>One Resumify account per person. Accounts found gaming credit systems (including the referral program) in bad faith may be suspended.</li>
      </ul>
    </section>

    <section>
      <h2>3. Plans and credits</h2>
      <p>
        Resumify offers a free Basic plan and paid Pro / Pro Max plans. Each plan grants a fixed
        number of AI-powered actions ("credits") — resume reviews and coach chats — that reset
        when a paid plan renews. Paid plans are valid for 30 days from purchase; unused credits
        do not roll over past that window. Referral and promotional bonus credits, where granted,
        are added on top of your plan's normal allowance.
      </p>
    </section>

    <section>
      <h2>4. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the service to generate misleading, fraudulent, or plagiarized resume content presented as someone else's genuine work history.</li>
        <li>Attempt to bypass credit limits, rate limits, or plan restrictions.</li>
        <li>Upload files containing malware or attempt to exploit our upload or AI pipelines.</li>
        <li>Scrape, resell, or redistribute our service or the output of our AI features without permission.</li>
        <li>Impersonate another person or misuse the recruiter proctored-testing tools to gain an unfair advantage.</li>
      </ul>
    </section>

    <section>
      <h2>5. AI-generated content</h2>
      <p>
        Resume reviews, rewrites, cover letters, and interview feedback are generated by AI models
        and are provided for guidance only. They are not a guarantee of interview or job outcomes,
        and we recommend you review all AI-generated content for accuracy before using it. You
        remain responsible for the resumes and applications you ultimately submit to employers.
      </p>
    </section>

    <section>
      <h2>6. Recruiter and job board terms</h2>
      <p>
        Recruiter accounts are approved manually and may post job listings, review applicants, and
        run proctored assessments. Recruiters agree to use candidate data (resumes, test results)
        solely for evaluating that candidate's application, not for any other purpose, and to
        comply with applicable employment and data protection laws.
      </p>
    </section>

    <section>
      <h2>7. Payments</h2>
      <p>
        Payments are processed by Razorpay. Prices are shown in Indian Rupees (INR) and are
        inclusive of applicable taxes unless stated otherwise. See our{' '}
        <a href="/Refund-Policy">Refund &amp; Cancellation Policy</a> for details on refunds.
      </p>
    </section>

    <section>
      <h2>8. Suspension and termination</h2>
      <p>
        We may suspend or terminate an account that violates these Terms, including abuse of the
        AI pipeline, credit systems, or the proctored testing tools. You can appeal a suspension
        from within the app. You may delete your own account at any time from your Account page.
      </p>
    </section>

    <section>
      <h2>9. Disclaimer of warranties</h2>
      <p>
        Resumify is provided "as is". We do not guarantee uninterrupted or error-free service, and
        we are not liable for any employment outcome, missed opportunity, or decision made based
        on AI-generated content.
      </p>
    </section>

    <section>
      <h2>10. Changes to these terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of Resumify after a change
        means you accept the updated Terms.
      </p>
    </section>

    <section>
      <h2>11. Contact us</h2>
      <p>
        Questions about these Terms? Email us at{' '}
        <a href="mailto:support@resumeenhancer.com">support@resumeenhancer.com</a>.
      </p>
    </section>
  </LegalPage>
)

export default TermsAndConditions
